# Generated by Django 5.1.12 on 2025-09-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pantalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=9)),
                ("contorno_cadera", models.IntegerField()),
                ("altura_cadera", models.IntegerField()),
                ("contorno_cintura", models.IntegerField()),
                ("largo_pierna", models.IntegerField()),
                ("largo_tiro", models.IntegerField()),
                ("largo_rodilla", models.IntegerField()),
                ("ancho_pantalon", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("contrasena", models.CharField(max_length=20)),
            ],
        ),
    ]
